gitlab:
  - .gitlab-ci.yml

github:
  - .github/**/*

documentation:
  - docs/**/*

test:
  - test/**/*
  - jest.config.js

lint:
  - .eslint*
  - .prettier*
  - .markdownlint*
  - .editorconfig
  - commitlint*

config:
  - tsconfig.json
  - .nvmrc

env:
  - .env.*

it:
  - .gitignore
  - .gitattributes
  - .gitmodules

build:
  - package.json
  - yarn.lock
  - package-lock.json

editor:
  - .prettier.mjs

src:
  - src/**/*
