name: CICD

on:
  push:
    branches: ['main']

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.9.1]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install
        env:
          CI: true

      - name: Unit Test
        env:
          JEST_JUNIT_OUTPUT: 'reports/unit.xml'
        run: |
          yarn test:coverage \
          --ci \
          --coverageDirectory ./reports/unit-coverage \
          __test__/unit
      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn run build
  CD:
    needs: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.9.1]

    # steps:
    #   - name: ConfigureAWS
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: {}

    #   - name: Deploy
    #     id: deploy
    #     run: |
    #       aws deploy create-deployment \
    #       --application-name {} \
    #       --deployment-group-name {} \
    #       --deployment-config-name {} \
    #       --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
